version: "3.7"
networks:
  app-network:
    driver: bridge
services:
  app:
    networks:
      - app-network
    build: .
    container_name: rentx
    ports:
      - "3333:3333"
    links:
      - database_ignite
    volumes:
      - ".:/usr/app"
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rentx
    volumes:
      - "pgdata:/data/postgres"
    networks:
      - app-network
volumes:
  pgdata:
    driver: local
